/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/projects/known": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Known Projects
         * @description Return all known projects, ordered by ``last_opened_at`` DESC.
         */
        get: operations["list_known_projects_api_projects_known_get"];
        put?: never;
        /**
         * Register Known Project
         * @description Register or update a project (idempotent upsert).
         */
        post: operations["register_known_project_api_projects_known_post"];
        /**
         * Remove Known Project
         * @description Remove a project from the registry by ``path``.
         */
        delete: operations["remove_known_project_api_projects_known_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description List directories containing a project meta directory.
         */
        get: operations["list_projects_api_project_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate Project */
        get: operations["validate_project_api_project_validate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scan Project
         * @description Inspect the project root for onboarding.
         *
         *     Returns three groups: important files (README, pyproject.toml, …),
         *     top-level folders, and a guidance-file probe for each registered
         *     agent engine (e.g. ``CLAUDE.md`` for Claude). Engine metadata comes
         *     from the runtime classes themselves — see
         *     ``AVAILABLE_RUNTIME_CLASSES``.
         */
        get: operations["scan_project_api_project_scan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/init-engine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Init Engine
         * @description Bootstrap an engine's guidance file (e.g. CLAUDE.md) for a project.
         *
         *     Writes the runtime's ``guidance_template`` to ``path/<guidance_file>``
         *     when the file is missing. Idempotent — if the file already exists,
         *     leaves it alone and reports ``created=false``. Engine metadata
         *     (filename + template) comes from the runtime class itself, so adding
         *     a new engine doesn't touch this endpoint.
         */
        post: operations["init_engine_api_project_init_engine_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Files
         * @description List project directory tree (files and folders).
         */
        get: operations["list_files_api_project_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/file/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read File
         * @description Read a text file's contents. Path is relative to project root.
         */
        get: operations["read_file_api_file_read_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/file/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read File Raw
         * @description Serve a file's raw content with appropriate content type (for images etc.).
         *
         *     Accepts absolute paths for cases where the agent produces files outside the
         *     project tree (e.g. temporary screenshot files).  Relative paths are resolved
         *     inside the project root without traversal validation so they are safe.
         */
        get: operations["read_file_raw_api_file_raw_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/file/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Browse Files
         * @description Open a native file dialog and return selected absolute paths.
         */
        post: operations["browse_files_api_file_browse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/file/write": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Write File
         * @description Write content to a file. Path is relative to project root.
         */
        post: operations["write_file_api_file_write_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/file/open-external": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open External
         * @description Open a file in an external editor.
         */
        post: operations["open_external_api_file_open_external_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/list-dirs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Dirs
         * @description List subdirectories of *base* matching *prefix*. For path autocompletion.
         */
        get: operations["list_dirs_api_fs_list_dirs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/mkdir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Make Directory
         * @description Create a directory (and parents) at the given path.
         */
        post: operations["make_directory_api_fs_mkdir_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse Folder
         * @description Open a native OS folder picker dialog and return the selected path.
         */
        get: operations["browse_folder_api_fs_browse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server Info */
        get: operations["server_info_api_server_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DirListResponse */
        DirListResponse: {
            /** Dirs */
            dirs: string[];
        };
        /** FileBrowseResponse */
        FileBrowseResponse: {
            /** Paths */
            paths: string[];
            /** Error */
            error?: string | null;
        };
        /** FileEntry */
        FileEntry: {
            /** Path */
            path: string;
            /** Name */
            name: string;
            /** Isdir */
            isDir: boolean;
            /** Depth */
            depth: number;
        };
        /** FileReadResponse */
        FileReadResponse: {
            /** Content */
            content: string;
            /** Path */
            path: string;
            /** Name */
            name: string;
            /** Size */
            size: number;
        };
        /** FileWriteResponse */
        FileWriteResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Path */
            path: string;
        };
        /** FolderPickResponse */
        FolderPickResponse: {
            /** Path */
            path?: string | null;
            /** Error */
            error?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * InitEngineRequest
         * @description Body of ``POST /api/project/init-engine``.
         */
        InitEngineRequest: {
            /** Engine */
            engine: string;
            /** Path */
            path: string;
        };
        /**
         * InitEngineResponse
         * @description Result of writing an engine's guidance template.
         */
        InitEngineResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Created */
            created: boolean;
            /** File */
            file: string;
            /** Init Command */
            init_command?: string | null;
        };
        /** KnownProjectResponse */
        KnownProjectResponse: {
            /** Path */
            path: string;
            /** Name */
            name: string;
            /** Registered At */
            registered_at: string;
            /** Last Opened At */
            last_opened_at: string;
        };
        /** OkResponse */
        OkResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** OpenExternalResponse */
        OpenExternalResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Terminal */
            terminal?: string | null;
            /** Error */
            error?: string | null;
        };
        /** ProjectFilesResponse */
        ProjectFilesResponse: {
            /** Entries */
            entries: components["schemas"]["FileEntry"][];
        };
        /** ProjectInfo */
        ProjectInfo: {
            /** Path */
            path: string;
            /** Name */
            name: string;
        };
        /** ProjectListResponse */
        ProjectListResponse: {
            /** Projects */
            projects: components["schemas"]["ProjectInfo"][];
        };
        /** ProjectScanResponse */
        ProjectScanResponse: {
            /** Important Files */
            important_files: components["schemas"]["ScanFile"][];
            /** Top Folders */
            top_folders: components["schemas"]["ScanFolder"][];
            /** Engine Guidance */
            engine_guidance: components["schemas"]["ScanEngineGuidance"][];
        };
        /** ProjectValidateResponse */
        ProjectValidateResponse: {
            /**
             * State
             * @enum {string}
             */
            state: "initialized" | "new" | "existing";
            /** Path */
            path: string;
            /** Name */
            name: string;
            /** Exists */
            exists: boolean;
        };
        /**
         * ScanEngineGuidance
         * @description Per-engine guidance-file probe result.
         *
         *     Each ``IAgentRuntime`` declares the repo-root file it expects to
         *     read (e.g. ``CLAUDE.md``) and the shell command that creates it.
         *     The onboarding scanner reports whether that file is present so the
         *     UI can prompt the user to run the init command if not.
         */
        ScanEngineGuidance: {
            /** Engine */
            engine: string;
            /** Display Name */
            display_name: string;
            /** File */
            file: string;
            /** Found */
            found: boolean;
            /** Init Command */
            init_command?: string | null;
        };
        /**
         * ScanFile
         * @description A high-signal file found at the project root.
         */
        ScanFile: {
            /** Name */
            name: string;
            /** Size */
            size: number;
            /** Description */
            description: string;
        };
        /**
         * ScanFolder
         * @description A top-level directory inside the project root.
         */
        ScanFolder: {
            /** Name */
            name: string;
            /** Entry Count */
            entry_count: number;
        };
        /** ServerInfoResponse */
        ServerInfoResponse: {
            /** Hostname */
            hostname: string;
            /** Lanips */
            lanIps: string[];
            tailscale: components["schemas"]["TailscaleInfoResponse"];
            /** Version */
            version: string;
        };
        /** TailscaleInfoResponse */
        TailscaleInfoResponse: {
            /** Ip */
            ip?: string | null;
            /** Hostname */
            hostname?: string | null;
            /**
             * Active
             * @default false
             */
            active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** _MkdirBody */
        _MkdirBody: {
            /** Path */
            path: string;
        };
        /** _OkResponse */
        _OkResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** _OpenExternalBody */
        _OpenExternalBody: {
            /** Project */
            project: string;
            /** Path */
            path: string;
            /** Editor */
            editor: string;
        };
        /** _RegisterBody */
        _RegisterBody: {
            /** Path */
            path: string;
            /** Name */
            name: string;
        };
        /** _WriteFileBody */
        _WriteFileBody: {
            /** Project */
            project: string;
            /** Path */
            path: string;
            /** Content */
            content: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_known_projects_api_projects_known_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnownProjectResponse"][];
                };
            };
        };
    };
    register_known_project_api_projects_known_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_RegisterBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_known_project_api_projects_known_delete: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_projects_api_project_list_get: {
        parameters: {
            query?: {
                base?: string;
                max_depth?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_project_api_project_validate_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_project_api_project_scan_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    init_engine_api_project_init_engine_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitEngineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitEngineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_files_api_project_files_get: {
        parameters: {
            query: {
                path: string;
                max_depth?: number;
                show_hidden?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectFilesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_file_api_file_read_get: {
        parameters: {
            query: {
                project: string;
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_file_raw_api_file_raw_get: {
        parameters: {
            query: {
                project: string;
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    browse_files_api_file_browse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileBrowseResponse"];
                };
            };
        };
    };
    write_file_api_file_write_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_WriteFileBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileWriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_external_api_file_open_external_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_OpenExternalBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenExternalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_dirs_api_fs_list_dirs_get: {
        parameters: {
            query: {
                base: string;
                prefix?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    make_directory_api_fs_mkdir_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_MkdirBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    browse_folder_api_fs_browse_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderPickResponse"];
                };
            };
        };
    };
    server_info_api_server_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerInfoResponse"];
                };
            };
        };
    };
}
