#!/usr/bin/env bun
// Build a single-file `thinkrail-pi` executable: embed the built web UI into `compiled-entry.ts` and
// `bun build --compile` it. Bun bundles the host + the `bun-pty` native lib automatically; this script's
// only job is wiring the web assets in. Run `bun run build:web` first (we error if the build is missing).
//
// Usage:  bun run scripts/build-binary.ts [--target=<bun-target>]
//   --target  a Bun cross-compile target (e.g. bun-darwin-arm64 / bun-linux-x64 / bun-windows-x64).
//             Omitted → the host platform. Each target bundles that platform's matching bun-pty lib.

import { createHash } from "node:crypto";
import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	statSync,
	writeFileSync,
} from "node:fs";
import { join, relative, resolve, sep } from "node:path";

const cliDir = resolve(import.meta.dir, "..");
const repoRoot = resolve(cliDir, "..", "..");
const webDist = join(repoRoot, "apps", "web", "dist");
const generatedPath = join(cliDir, "src", "web-assets.generated.ts");
const entryPath = join(cliDir, "src", "compiled-entry.ts");
const outDir = join(cliDir, "dist");

/** Every file under `dir`, recursively (absolute paths). */
function listFiles(dir: string): string[] {
	const out: string[] = [];
	for (const name of readdirSync(dir)) {
		const full = join(dir, name);
		if (statSync(full).isDirectory()) out.push(...listFiles(full));
		else out.push(full);
	}
	return out;
}

/** Write `src/web-assets.generated.ts`: a `with { type: "file" }` import per dist file + the manifest. */
function generateManifest(): void {
	if (!existsSync(join(webDist, "index.html"))) {
		throw new Error(`web build not found at ${webDist} — run \`bun run build:web\` first.`);
	}
	const files = listFiles(webDist).sort();
	const hash = createHash("sha256");
	const imports: string[] = [];
	const entries: string[] = [];
	files.forEach((file, i) => {
		const route = relative(webDist, file).split(sep).join("/");
		hash.update(route).update(readFileSync(file));
		imports.push(`import a${i} from "../../web/dist/${route}" with { type: "file" };`);
		entries.push(`\t{ route: ${JSON.stringify(route)}, data: a${i} },`);
	});
	const version = hash.digest("hex").slice(0, 16);
	writeFileSync(
		generatedPath,
		`// GENERATED by scripts/build-binary.ts — do not edit. Embeds apps/web/dist into the single-file binary.\n${imports.join("\n")}\n\nexport const webAssetsVersion = ${JSON.stringify(version)};\nexport const embeddedWebAssets = [\n${entries.join("\n")}\n];\n`,
	);
}

const target = process.argv.find((a) => a.startsWith("--target="))?.slice("--target=".length);
const outName = target ? `thinkrail-pi-${target.replace(/^bun-/, "")}` : "thinkrail-pi";
const outFile = join(outDir, outName);

mkdirSync(outDir, { recursive: true });
generateManifest();
try {
	const proc = Bun.spawnSync(
		["bun", "build", "--compile", `--target=${target ?? "bun"}`, entryPath, "--outfile", outFile],
		{ stdout: "inherit", stderr: "inherit", cwd: cliDir },
	);
	if (!proc.success) process.exit(proc.exitCode ?? 1);
} finally {
	// The generated module is build-only — keep the working tree (and tsc) clean.
	rmSync(generatedPath, { force: true });
}
console.log(`\nBuilt single-file binary: ${outFile}`);
