#!/usr/bin/env bun
// Build a single-file `thinkrail` executable: embed the built web UI + the bundled pi extensions into
// generated modules and `bun build --compile` `compiled-entry.ts`. Bun bundles the host + the `bun-pty`
// native lib automatically; this script wires in the two things it can't: the web assets (a directory the
// host serves) and the bundled extensions (which the server path-loads out of `node_modules` in dev — a
// binary has none, so their entries are value-imported and their skills embedded as files). Run
// `bun run build:web` first (we error if the build is missing).
//
// Usage:  bun run scripts/build-binary.ts [--target=<bun-target>]
//   --target  a Bun cross-compile target (e.g. bun-darwin-arm64 / bun-linux-x64 / bun-windows-x64).
//             Omitted → the host platform. Each target bundles that platform's matching bun-pty lib.

import { createHash } from "node:crypto";
import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	statSync,
	writeFileSync,
} from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, relative, resolve, sep } from "node:path";

const cliDir = resolve(import.meta.dir, "..");
const repoRoot = resolve(cliDir, "..", "..");
const webDist = join(repoRoot, "apps", "web", "dist");
const webGeneratedPath = join(cliDir, "src", "web-assets.generated.ts");
const extGeneratedPath = join(cliDir, "src", "bundled-extensions.generated.ts");
const entryPath = join(cliDir, "src", "compiled-entry.ts");
const outDir = join(cliDir, "dist");

/** Every file under `dir`, recursively (absolute paths). */
function listFiles(dir: string): string[] {
	const out: string[] = [];
	for (const name of readdirSync(dir)) {
		const full = join(dir, name);
		if (statSync(full).isDirectory()) out.push(...listFiles(full));
		else out.push(full);
	}
	return out;
}

/** `{ route, data }` manifest source for `files`, rooted at `rootDir`; returns imports + entries + hash. */
function embedFiles(
	files: { root: string; file: string }[],
	importPrefix: string,
): { imports: string[]; entries: string[]; version: string } {
	const hash = createHash("sha256");
	const imports: string[] = [];
	const entries: string[] = [];
	const seen = new Set<string>();
	files.forEach(({ root, file }, i) => {
		const route = relative(root, file).split(sep).join("/");
		if (seen.has(route)) throw new Error(`duplicate embedded route: ${route}`);
		seen.add(route);
		hash.update(route).update(readFileSync(file));
		imports.push(`import ${importPrefix}${i} from ${JSON.stringify(file)} with { type: "file" };`);
		entries.push(`\t{ route: ${JSON.stringify(route)}, data: ${importPrefix}${i} },`);
	});
	return { imports, entries, version: hash.digest("hex").slice(0, 16) };
}

/** Write `src/web-assets.generated.ts`: a `with { type: "file" }` import per dist file + the manifest. */
function generateWebManifest(): void {
	if (!existsSync(join(webDist, "index.html"))) {
		throw new Error(`web build not found at ${webDist} — run \`bun run build:web\` first.`);
	}
	const files = listFiles(webDist)
		.sort()
		.map((file) => ({ root: webDist, file }));
	const { imports, entries, version } = embedFiles(files, "a");
	writeFileSync(
		webGeneratedPath,
		`// GENERATED by scripts/build-binary.ts — do not edit. Embeds apps/web/dist into the single-file binary.\n${imports.join("\n")}\n\nexport const webAssetsVersion = ${JSON.stringify(version)};\nexport const embeddedWebAssets = [\n${entries.join("\n")}\n];\n`,
	);
}

/**
 * Write `src/bundled-extensions.generated.ts`: value-imports of the four bundled extension entries
 * (resolved from the *server package's* module context — they aren't deps of `cli`; Bun compiles the raw
 * `.ts` + their deps into the binary) + the skills files the dev path wires via `additionalSkillPaths`
 * (`pi-spec-graph`, `pi-thinkrail-workflow` — parity with the server's run-from-source wiring).
 */
function generateBundledExtensions(): void {
	const serverRequire = createRequire(join(repoRoot, "packages", "server", "package.json"));
	const entrySpecifiers = [
		"pi-web-access/index.ts",
		"pi-visualize/index.ts",
		"pi-spec-graph/index.ts",
		"pi-thinkrail-workflow/index.ts",
	];
	const entryPaths = entrySpecifiers.map((specifier) => serverRequire.resolve(specifier));
	const factoryImports = entryPaths.map((path, i) => `import x${i} from ${JSON.stringify(path)};`);
	const skillRoots = [entryPaths[2], entryPaths[3]].map((entry) => join(dirname(entry), "skills"));
	const skillFiles = skillRoots.flatMap((root) =>
		listFiles(root)
			.sort()
			.map((file) => ({ root, file })),
	);
	const { imports, entries, version } = embedFiles(skillFiles, "s");
	writeFileSync(
		extGeneratedPath,
		`// GENERATED by scripts/build-binary.ts — do not edit. Value-imports the bundled pi extensions and\n// embeds their skills into the single-file binary.\n${factoryImports.join("\n")}\n${imports.join("\n")}\n\nexport const bundledExtensionFactories = [x0, x1, x2, x3];\nexport const bundledSkillsVersion = ${JSON.stringify(version)};\nexport const embeddedSkillFiles = [\n${entries.join("\n")}\n];\n`,
	);
}

const target = process.argv.find((a) => a.startsWith("--target="))?.slice("--target=".length);
const outName = target ? `thinkrail-${target.replace(/^bun-/, "")}` : "thinkrail";
const outFile = join(outDir, outName);

mkdirSync(outDir, { recursive: true });
generateWebManifest();
generateBundledExtensions();
try {
	const proc = Bun.spawnSync(
		["bun", "build", "--compile", `--target=${target ?? "bun"}`, entryPath, "--outfile", outFile],
		{ stdout: "inherit", stderr: "inherit", cwd: cliDir },
	);
	if (!proc.success) process.exit(proc.exitCode ?? 1);
} finally {
	// The generated modules are build-only — keep the working tree (and tsc) clean.
	rmSync(webGeneratedPath, { force: true });
	rmSync(extGeneratedPath, { force: true });
}
console.log(`\nBuilt single-file binary: ${outFile}`);
