blank_issues_enabled: true
contact_links:
  - name: Code of Conduct
    url: https://github.com/jetbrains#code-of-conduct
    about: This project follows the JetBrains Open Source and Community Code of Conduct.
