/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ThinkRailRpcPayloads =
  | LabeledOption
  | RuntimeFlag
  | RuntimeIdentity
  | RuntimeCapabilities
  | RuntimesListResponse
  | RuntimesCapabilitiesRequest
  | InvalidCapabilityValueData;
export type Value = string;
export type Label = string;
export type Key = string;
export type Label1 = string;
export type Type = "boolean";
export type Default = boolean;
export type Description = string;
export type Runtimetype = "claude";
export type Displayname = string;
export type Permissionmodes = LabeledOption[];
export type Effortlevels = LabeledOption[];
export type Models = LabeledOption[];
export type Flags = RuntimeFlag[];
export type Runtimes = RuntimeIdentity[];
export type Runtimetype1 = "claude";
export type Field = string;
export type Value1 = string;
export type Runtimetype2 = "claude";
export type Allowed = string[];

/**
 * A value the backend accepts, plus a display label for the UI.
 *
 * Used uniformly for permission modes, effort levels, and models on
 * ``RuntimeCapabilities``. ``extra="forbid"`` surfaces typos at parse time.
 */
export interface LabeledOption {
  value: Value;
  label: Label;
}
/**
 * A runtime-declared option toggle, surfaced as a control in settings.
 *
 * Each runtime advertises its own flags; the frontend renders one control
 * per flag and stores the chosen value in ``AgentConfig.flags`` keyed by
 * ``key``. ``type`` is a discriminator (only ``"boolean"`` today) so other
 * value kinds can be added without changing the shape.
 */
export interface RuntimeFlag {
  key: Key;
  label: Label1;
  type: Type;
  default: Default;
  description?: Description;
}
/**
 * Lightweight ``{runtimeType, displayName}`` pair for ``runtimes/list``.
 */
export interface RuntimeIdentity {
  runtimeType: Runtimetype;
  displayName: Displayname;
}
/**
 * What a runtime accepts for the user-tunable fields.
 *
 * Order is contract: position 0 of ``permission_modes`` / ``effort_levels`` /
 * ``models`` is the runtime's default (cold-start picks ``[0].value``).
 */
export interface RuntimeCapabilities {
  permissionModes: Permissionmodes;
  effortLevels: Effortlevels;
  models: Models;
  flags?: Flags;
}
/**
 * Wire payload returned by ``runtimes/list``.
 */
export interface RuntimesListResponse {
  runtimes: Runtimes;
}
/**
 * Wire payload accepted by ``runtimes/capabilities``.
 */
export interface RuntimesCapabilitiesRequest {
  runtimeType: Runtimetype1;
}
/**
 * ``data`` payload attached to ``INVALID_CAPABILITY_VALUE`` (-32032).
 */
export interface InvalidCapabilityValueData {
  field: Field;
  value: Value1;
  runtimeType: Runtimetype2;
  allowed: Allowed;
}
