/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WsEvents =
  | SessionStartEvent
  | TextDeltaEvent
  | ToolCallStartEvent
  | ToolCallEndEvent
  | SubagentStartEvent
  | SubagentEndEvent
  | CompactEvent
  | ProgressEvent
  | NotificationEvent
  | PermissionDeniedEvent
  | ReadyEvent
  | TurnCompleteEvent
  | InterruptedEvent
  | ErrorEvent
  | DoneEvent
  | AskUserQuestionEvent
  | ConfirmActionEvent
  | SuggestSessionEvent
  | SuggestDescriptionEvent
  | SuggestStepEvent
  | RequestResolvedEvent
  | RequestExpiredEvent
  | UserMessageEvent;
export type Bonsaisid = string;
export type Sessionid = string;
export type Eventtype = "sessionStart";
export type Sessionid1 = string;
export type Systemprompt = string;
export type Inferencebudgettokens = number | null;
export type Bonsaisid1 = string;
export type Sessionid2 = string;
export type Eventtype1 = "textDelta";
export type Text = string;
export type Agentid = string | null;
export type Bonsaisid2 = string;
export type Sessionid3 = string;
export type Eventtype2 = "toolCallStart";
export type Tooluseid = string;
export type Toolname = string;
export type Agentid1 = string | null;
export type Bonsaisid3 = string;
export type Sessionid4 = string;
export type Eventtype3 = "toolCallEnd";
export type Tooluseid1 = string;
export type Toolname1 = string;
export type Output = string;
export type Iserror = boolean;
export type Agentid2 = string | null;
export type Bonsaisid4 = string;
export type Sessionid5 = string;
export type Eventtype4 = "subagentStart";
export type Agentid3 = string;
export type Agenttype = string;
export type Bonsaisid5 = string;
export type Sessionid6 = string;
export type Eventtype5 = "subagentEnd";
export type Agentid4 = string;
export type Bonsaisid6 = string;
export type Sessionid7 = string;
export type Eventtype6 = "compact";
export type Trigger = string;
export type Pretokens = number;
export type Bonsaisid7 = string;
export type Sessionid8 = string;
export type Eventtype7 = "progress";
export type Message = string;
export type Bonsaisid8 = string;
export type Sessionid9 = string;
export type Eventtype8 = "notification";
export type Message1 = string;
export type Type = string | null;
export type Bonsaisid9 = string;
export type Sessionid10 = string;
export type Eventtype9 = "permissionDenied";
export type Toolname2 = string | null;
export type Bonsaisid10 = string;
export type Sessionid11 = string;
export type Eventtype10 = "ready";
export type Bonsaisid11 = string;
export type Sessionid12 = string;
export type Eventtype11 = "turnComplete";
export type Turncostusd = number;
export type Costusd = number;
export type Turns = number;
export type Turnturns = number;
export type Durationms = number;
export type Iterations = {
  [k: string]: unknown;
}[];
export type Contextwindow = number;
export type Result = string;
export type Bonsaisid12 = string;
export type Sessionid13 = string;
export type Eventtype12 = "interrupted";
export type Turncostusd1 = number;
export type Costusd1 = number;
export type Turns1 = number;
export type Turnturns1 = number;
export type Durationms1 = number;
export type Iterations1 = {
  [k: string]: unknown;
}[];
export type Contextwindow1 = number;
export type Bonsaisid13 = string;
export type Sessionid14 = string;
export type Eventtype13 = "error";
export type Turncostusd2 = number;
export type Costusd2 = number;
export type Turns2 = number;
export type Turnturns2 = number;
export type Durationms2 = number;
export type Iterations2 = {
  [k: string]: unknown;
}[];
export type Contextwindow2 = number;
export type Subtype = string;
export type Errors = string[];
export type Result1 = string;
export type Bonsaisid14 = string;
export type Sessionid15 = string;
export type Eventtype14 = "done";
export type Result2 = string;
export type Costusd3 = number;
export type Turns3 = number;
export type Durationms3 = number;
export type Summary = string | null;
export type Path = string;
export type Label = string | null;
export type Openondone = boolean;
export type Artifacts = OutcomeArtifact[];
export type Type1 = "create_ticket";
export type Id = string;
export type Title = string;
export type Body = string | null;
export type State = "pending" | "applied";
export type Type2 = "start_session";
export type Id1 = string;
export type Title1 = string;
export type Description = string | null;
export type Skillid = string;
export type Prompt = string | null;
export type Primary = boolean;
export type Type3 = "navigate";
export type Id2 = string;
export type Title2 = string;
export type Description1 = string | null;
export type Target = "board" | "specs" | "graph" | "files";
export type Actions = (CreateTicketAction | StartSessionAction | NavigateAction)[];
export type Bonsaisid15 = string;
export type Sessionid16 = string;
export type Eventtype15 = "askUserQuestion";
export type Question1 = string;
export type Header = string;
export type Label1 = string;
export type Description2 = string;
export type Options = QuestionOption[];
export type Multiselect = boolean;
export type Questions = Question[];
export type Attempt = number;
export type Requestid = string;
export type Bonsaisid16 = string;
export type Sessionid17 = string;
export type Eventtype16 = "confirmAction";
export type Toolname3 = string;
export type Tooluseid2 = string | null;
export type Attempt1 = number;
export type Requestid1 = string;
export type Description3 = string | null;
export type Bonsaisid17 = string;
export type Sessionid18 = string;
export type Eventtype17 = "suggestSession";
export type Skill = string;
export type Specids = string[];
export type Name = string;
export type Reason = string;
export type Prompt1 = string | null;
export type Requestid2 = string;
export type Bonsaisid18 = string;
export type Sessionid19 = string;
export type Eventtype18 = "suggestDescription";
export type Description4 = string;
export type Section = string;
export type Requestid3 = string;
export type Bonsaisid19 = string;
export type Sessionid20 = string;
export type Eventtype19 = "suggestStep";
export type Ticketid = string;
export type Stepnumber = number;
export type Steptitle = string;
export type Skill1 = string;
export type Inputspecids = string[];
export type Agentinstructions = string;
export type Reason1 = string;
export type Requestid4 = string;
export type Bonsaisid20 = string;
export type Sessionid21 = string;
export type Eventtype20 = "requestResolved";
export type Requestid5 = string;
export type Response = {
  [k: string]: unknown;
} | null;
export type Bonsaisid21 = string;
export type Sessionid22 = string;
export type Eventtype21 = "requestExpired";
export type Requestid6 = string;
export type Reason2 = string;
export type Bonsaisid22 = string;
export type Sessionid23 = string;
export type Eventtype22 = "userMessage";
export type Text1 = string;
export type Ismarkdown = boolean;

export interface SessionStartEvent {
  bonsaiSid: Bonsaisid;
  sessionId: Sessionid;
  eventType: Eventtype;
  payload: SessionStartPayload;
}
/**
 * Emitted once when the SDK session initializes.
 */
export interface SessionStartPayload {
  sessionId?: Sessionid1;
  systemPrompt?: Systemprompt;
  inferenceBudgetTokens?: Inferencebudgettokens;
  [k: string]: unknown;
}
export interface TextDeltaEvent {
  bonsaiSid: Bonsaisid1;
  sessionId: Sessionid2;
  eventType: Eventtype1;
  payload: TextDeltaPayload;
}
/**
 * A chunk of streamed assistant text.
 */
export interface TextDeltaPayload {
  text: Text;
  agentId?: Agentid;
}
export interface ToolCallStartEvent {
  bonsaiSid: Bonsaisid2;
  sessionId: Sessionid3;
  eventType: Eventtype2;
  payload: ToolCallStartPayload;
}
/**
 * Agent invokes a tool.
 */
export interface ToolCallStartPayload {
  toolUseId: Tooluseid;
  toolName: Toolname;
  toolInput: Toolinput;
  agentId?: Agentid1;
}
export interface Toolinput {
  [k: string]: unknown;
}
export interface ToolCallEndEvent {
  bonsaiSid: Bonsaisid3;
  sessionId: Sessionid4;
  eventType: Eventtype3;
  payload: ToolCallEndPayload;
}
/**
 * Tool result returned to the agent.
 */
export interface ToolCallEndPayload {
  toolUseId: Tooluseid1;
  toolName?: Toolname1;
  output: Output;
  isError?: Iserror;
  agentId?: Agentid2;
}
export interface SubagentStartEvent {
  bonsaiSid: Bonsaisid4;
  sessionId: Sessionid5;
  eventType: Eventtype4;
  payload: SubagentStartPayload;
}
/**
 * A child agent was spawned.
 */
export interface SubagentStartPayload {
  agentId: Agentid3;
  agentType: Agenttype;
}
export interface SubagentEndEvent {
  bonsaiSid: Bonsaisid5;
  sessionId: Sessionid6;
  eventType: Eventtype5;
  payload: SubagentEndPayload;
}
/**
 * Child agent finished.
 */
export interface SubagentEndPayload {
  agentId: Agentid4;
}
export interface CompactEvent {
  bonsaiSid: Bonsaisid6;
  sessionId: Sessionid7;
  eventType: Eventtype6;
  payload: CompactPayload;
}
/**
 * Context compaction happened.
 */
export interface CompactPayload {
  trigger: Trigger;
  preTokens?: Pretokens;
}
export interface ProgressEvent {
  bonsaiSid: Bonsaisid7;
  sessionId: Sessionid8;
  eventType: Eventtype7;
  payload: ProgressPayload;
}
/**
 * Ephemeral status message (not persisted).
 */
export interface ProgressPayload {
  message?: Message;
}
export interface NotificationEvent {
  bonsaiSid: Bonsaisid8;
  sessionId: Sessionid9;
  eventType: Eventtype8;
  payload: NotificationPayload;
}
/**
 * A user-visible message from the agent.
 */
export interface NotificationPayload {
  message?: Message1;
  type?: Type;
  [k: string]: unknown;
}
export interface PermissionDeniedEvent {
  bonsaiSid: Bonsaisid9;
  sessionId: Sessionid10;
  eventType: Eventtype9;
  payload: PermissionDeniedPayload;
}
/**
 * A tool was blocked by the SDK.
 */
export interface PermissionDeniedPayload {
  toolName?: Toolname2;
  [k: string]: unknown;
}
export interface ReadyEvent {
  bonsaiSid: Bonsaisid10;
  sessionId: Sessionid11;
  eventType: Eventtype10;
  payload: ReadyPayload;
}
/**
 * Session is idle and waiting for input.
 */
export interface ReadyPayload {}
export interface TurnCompleteEvent {
  bonsaiSid: Bonsaisid11;
  sessionId: Sessionid12;
  eventType: Eventtype11;
  payload: TurnCompletePayload;
}
/**
 * Agent completed a turn successfully.
 */
export interface TurnCompletePayload {
  turnCostUsd?: Turncostusd;
  costUsd?: Costusd;
  turns?: Turns;
  turnTurns?: Turnturns;
  durationMs?: Durationms;
  usage?: Usage;
  iterations?: Iterations;
  contextWindow?: Contextwindow;
  result?: Result;
}
export interface Usage {
  [k: string]: unknown;
}
export interface InterruptedEvent {
  bonsaiSid: Bonsaisid12;
  sessionId: Sessionid13;
  eventType: Eventtype12;
  payload: InterruptedPayload;
}
/**
 * Turn was cancelled by the user.
 */
export interface InterruptedPayload {
  turnCostUsd?: Turncostusd1;
  costUsd?: Costusd1;
  turns?: Turns1;
  turnTurns?: Turnturns1;
  durationMs?: Durationms1;
  usage?: Usage1;
  iterations?: Iterations1;
  contextWindow?: Contextwindow1;
}
export interface Usage1 {
  [k: string]: unknown;
}
export interface ErrorEvent {
  bonsaiSid: Bonsaisid13;
  sessionId: Sessionid14;
  eventType: Eventtype13;
  payload: ErrorPayload;
}
/**
 * Turn failed with an error.
 */
export interface ErrorPayload {
  turnCostUsd?: Turncostusd2;
  costUsd?: Costusd2;
  turns?: Turns2;
  turnTurns?: Turnturns2;
  durationMs?: Durationms2;
  usage?: Usage2;
  iterations?: Iterations2;
  contextWindow?: Contextwindow2;
  subtype?: Subtype;
  errors?: Errors;
  result?: Result1;
}
export interface Usage2 {
  [k: string]: unknown;
}
export interface DoneEvent {
  bonsaiSid: Bonsaisid14;
  sessionId: Sessionid15;
  eventType: Eventtype14;
  payload: DonePayload;
}
/**
 * Session closed gracefully after END_SIGNAL.
 */
export interface DonePayload {
  result?: Result2;
  costUsd?: Costusd3;
  turns?: Turns3;
  durationMs?: Durationms3;
  usage?: Usage3;
  outcome?: SessionOutcome | null;
}
export interface Usage3 {
  [k: string]: unknown;
}
/**
 * What to show on the done screen of a session.
 *
 * Built up by the agent via `session_finalize` (and optionally `session_queue_action`).
 * Persisted on the AgentTask so it survives reloads.
 */
export interface SessionOutcome {
  summary?: Summary;
  artifacts?: Artifacts;
  actions?: Actions;
}
/**
 * A file produced or finalized by the session — opened on the done screen.
 */
export interface OutcomeArtifact {
  path: Path;
  label?: Label;
  openOnDone?: Openondone;
}
/**
 * Queued ticket creation. Rendered as an 'Add to board' button.
 *
 * `state="pending"` until the user clicks; `state="applied"` once the ticket
 * has been created on the board.
 */
export interface CreateTicketAction {
  type?: Type1;
  id: Id;
  title: Title;
  body?: Body;
  state?: State;
}
/**
 * Recommended follow-up session. Rendered as a primary/secondary CTA.
 */
export interface StartSessionAction {
  type?: Type2;
  id: Id1;
  title: Title1;
  description?: Description;
  skillId: Skillid;
  prompt?: Prompt;
  primary?: Primary;
}
/**
 * UI navigation only — no agent or tool call.
 */
export interface NavigateAction {
  type?: Type3;
  id: Id2;
  title: Title2;
  description?: Description1;
  target: Target;
}
export interface AskUserQuestionEvent {
  bonsaiSid: Bonsaisid15;
  sessionId: Sessionid16;
  eventType: Eventtype15;
  payload: AskUserQuestionPayload;
}
/**
 * Agent needs answers from the user.
 */
export interface AskUserQuestionPayload {
  questions: Questions;
  attempt?: Attempt;
  requestId?: Requestid;
}
/**
 * A single question with selectable options.
 */
export interface Question {
  question: Question1;
  header: Header;
  options: Options;
  multiSelect?: Multiselect;
}
/**
 * A selectable option within a question.
 */
export interface QuestionOption {
  label: Label1;
  description: Description2;
}
export interface ConfirmActionEvent {
  bonsaiSid: Bonsaisid16;
  sessionId: Sessionid17;
  eventType: Eventtype16;
  payload: ConfirmActionPayload;
}
/**
 * Agent wants to use a tool and needs approval.
 */
export interface ConfirmActionPayload {
  toolName: Toolname3;
  toolInput?: Toolinput1;
  toolUseId?: Tooluseid2;
  attempt?: Attempt1;
  requestId?: Requestid1;
  description?: Description3;
}
export interface Toolinput1 {
  [k: string]: unknown;
}
export interface SuggestSessionEvent {
  bonsaiSid: Bonsaisid17;
  sessionId: Sessionid18;
  eventType: Eventtype17;
  payload: SuggestSessionPayload;
}
/**
 * Agent suggests creating a subsession.
 */
export interface SuggestSessionPayload {
  skill?: Skill;
  specIds?: Specids;
  name?: Name;
  reason?: Reason;
  prompt?: Prompt1;
  requestId?: Requestid2;
}
export interface SuggestDescriptionEvent {
  bonsaiSid: Bonsaisid18;
  sessionId: Sessionid19;
  eventType: Eventtype18;
  payload: SuggestDescriptionPayload;
}
/**
 * Agent suggests a session description.
 */
export interface SuggestDescriptionPayload {
  description: Description4;
  section?: Section;
  requestId?: Requestid3;
}
export interface SuggestStepEvent {
  bonsaiSid: Bonsaisid19;
  sessionId: Sessionid20;
  eventType: Eventtype19;
  payload: SuggestStepPayload;
}
/**
 * Orchestrator proposes the next plan step for execution.
 */
export interface SuggestStepPayload {
  ticketId?: Ticketid;
  stepNumber?: Stepnumber;
  stepTitle?: Steptitle;
  skill?: Skill1;
  inputSpecIds?: Inputspecids;
  agentInstructions?: Agentinstructions;
  reason?: Reason1;
  requestId?: Requestid4;
}
export interface RequestResolvedEvent {
  bonsaiSid: Bonsaisid20;
  sessionId: Sessionid21;
  eventType: Eventtype20;
  payload: RequestResolvedPayload;
}
/**
 * User responded to a pending request.
 */
export interface RequestResolvedPayload {
  requestId?: Requestid5;
  response?: Response;
}
export interface RequestExpiredEvent {
  bonsaiSid: Bonsaisid21;
  sessionId: Sessionid22;
  eventType: Eventtype21;
  payload: RequestExpiredPayload;
}
/**
 * Pending request timed out without a response.
 */
export interface RequestExpiredPayload {
  requestId?: Requestid6;
  reason?: Reason2;
}
export interface UserMessageEvent {
  bonsaiSid: Bonsaisid22;
  sessionId: Sessionid23;
  eventType: Eventtype22;
  payload: UserMessagePayload;
}
/**
 * Echoed user input, stored in the event log.
 */
export interface UserMessagePayload {
  text: Text1;
  isMarkdown?: Ismarkdown;
}
