export {
	acknowledgeProjectSkills,
	approveProjectMcpServer,
	closeProject,
	getProjects,
	initProject,
	inspectProjectPath,
	listProjects,
	listRecentProjects,
	openProject,
	setPiTrustSeed,
	setProjectGroupEnabled,
	setProjectMcpOverride,
	setProjectPublisher,
	setProjectSkillEnabled,
	setProjectTrust,
} from "./projects";
