#!/usr/bin/env bun

import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const repoRoot = resolve(import.meta.dir, "../../..");
const webSrc = join(repoRoot, "apps/web/src");
const THEME_SOURCES = ["styles/generated/colors.css", "styles/generated/spacing.css", "index.css"];
export const OUTPUT = resolve(import.meta.dir, "../src/ext/appTheme.generated.ts");
export const TOKENS_OUTPUT = join(repoRoot, "packages/contracts/src/extThemeTokens.generated.ts");

const LINE_WIDTH = 100;
const TAB_WIDTH = 2;

const stripComments = (css: string) => css.replace(/\/\*[\s\S]*?\*\//g, "");
const readWeb = (file: string) => readFileSync(join(webSrc, file), "utf8");

const themeBlocks = (css: string) => {
	const blocks: string[] = [];
	const source = stripComments(css);
	for (const match of source.matchAll(/@theme\b[^{]*\{/g)) {
		let depth = 0;
		for (let i = match.index + match[0].length - 1; i < source.length; i++) {
			if (source[i] === "{") depth++;
			else if (source[i] === "}" && --depth === 0) {
				blocks.push(
					source
						.slice(match.index, i + 1)
						.split("\n")
						.map((line) => line.trimEnd())
						.filter((line) => line.trim() !== "")
						.join("\n"),
				);
				break;
			}
		}
	}
	return blocks;
};

export const renderAppTheme = () => {
	const blocks = THEME_SOURCES.flatMap((file) => themeBlocks(readWeb(file)));
	return [
		`// GENERATED by packages/server/scripts/generate-ext-theme.ts from apps/web theme CSS. Do not edit.`,
		"export const APP_THEME_CSS =",
		`\t${JSON.stringify(blocks.join("\n"))};`,
		"",
	].join("\n");
};

const kebab = (key: string) => `--${key.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase()}`;

const declared = (css: string, pattern: RegExp) => [
	...new Set([...stripComments(css).matchAll(pattern)].map((match) => match[1] ?? "")),
];

const paletteTokens = () => {
	const schema = JSON.parse(readWeb("themes/theme.schema.json")) as {
		$defs: { colors: { properties: Record<string, unknown> } };
	};
	return Object.keys(schema.$defs.colors.properties).map(kebab);
};

export const themeTokenGroups = () => ({
	palette: paletteTokens(),
	role: declared(
		themeBlocks(readWeb("styles/generated/colors.css")).join("\n"),
		/--color-[a-z0-9-]+:\s*var\((--[a-z0-9-]+)\)/g,
	),
	radius: declared(readWeb("styles/tokens.css"), /(--radius-[a-z0-9-]+)\s*:/g),
	font: declared(readWeb("styles/generated/typography.css"), /(--tr-font-family-[a-z0-9-]+)\s*:/g),
});

const width = (line: string) => line.replace(/\t/g, " ".repeat(TAB_WIDTH)).length;

const renderGroup = (name: string, tokens: readonly string[]) => {
	const quoted = tokens.map((token) => JSON.stringify(token));
	const inline = `\t${name}: [${quoted.join(", ")}],`;
	return width(inline) <= LINE_WIDTH
		? [inline]
		: [`\t${name}: [`, ...quoted.map((token) => `\t\t${token},`), "\t],"];
};

export const renderThemeTokens = () =>
	[
		"// GENERATED by packages/server/scripts/generate-ext-theme.ts from apps/web theme sources. Do not edit.",
		"export const EXT_THEME_TOKEN_GROUPS = {",
		...Object.entries(themeTokenGroups()).flatMap(([name, tokens]) => renderGroup(name, tokens)),
		"} as const;",
		"",
	].join("\n");

if (import.meta.main) {
	writeFileSync(OUTPUT, renderAppTheme());
	writeFileSync(TOKENS_OUTPUT, renderThemeTokens());
}
