#!/usr/bin/env bun

import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const repoRoot = resolve(import.meta.dir, "../../..");
const webSrc = join(repoRoot, "apps/web/src");
const THEME_SOURCES = ["styles/generated/colors.css", "styles/generated/spacing.css", "index.css"];
export const OUTPUT = resolve(import.meta.dir, "../src/ext/appTheme.generated.ts");

const stripComments = (css: string) => css.replace(/\/\*[\s\S]*?\*\//g, "");

const themeBlocks = (css: string) => {
	const blocks: string[] = [];
	const source = stripComments(css);
	for (const match of source.matchAll(/@theme\b[^{]*\{/g)) {
		let depth = 0;
		for (let i = match.index + match[0].length - 1; i < source.length; i++) {
			if (source[i] === "{") depth++;
			else if (source[i] === "}" && --depth === 0) {
				blocks.push(
					source
						.slice(match.index, i + 1)
						.split("\n")
						.map((line) => line.trimEnd())
						.filter((line) => line.trim() !== "")
						.join("\n"),
				);
				break;
			}
		}
	}
	return blocks;
};

export const renderAppTheme = () => {
	const blocks = THEME_SOURCES.flatMap((file) =>
		themeBlocks(readFileSync(join(webSrc, file), "utf8")),
	);
	return [
		`// GENERATED by packages/server/scripts/generate-ext-theme.ts from apps/web theme CSS. Do not edit.`,
		"export const APP_THEME_CSS =",
		`\t${JSON.stringify(blocks.join("\n"))};`,
		"",
	].join("\n");
};

if (import.meta.main) {
	const next = renderAppTheme();
	if (process.argv.includes("--check")) {
		const current = readFileSync(OUTPUT, "utf8");
		if (current !== next) {
			console.error("appTheme.generated.ts is stale: run `bun run ext-theme:generate`");
			process.exit(1);
		}
	} else writeFileSync(OUTPUT, next);
}
