name: Nightly Build

on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      release_type: nightly
      tag_name: nightly-latest
      release_name: Nightly Build
