name: Nightly Build

on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      release_type: ${{ github.event_name == 'schedule' && 'nightly' || 'none' }}
      tag_name: ${{ github.event_name == 'schedule' && 'nightly-latest' || '' }}
      release_name: ${{ github.event_name == 'schedule' && 'Nightly Build' || '' }}
